### PR TITLE
updated version

### PR DESCRIPTION
**Pull request by ChrisBarker-NOAA**
@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by ChrisBarker-NOAA** [comment]
@lincrosenbach, 
@kfasolin,
@conda-forge/help-python

Could someone take a look at merge this?

I could really need an updated version.

**Comment by beckermr** [comment]
You need to bump @conda-forge/venusian to merge. The staged-recipes team has no permissions here.

**Comment by ChrisBarker-NOAA** [comment]
I thought I did that already.

@conda-forge/core:

What are we supposed to do when recipe maintainers are not responding? I've looked at the docs and haven't found a process identified.

Note that there have been multiple PRs on this one for updates for a few months -- so I'm not optimistic that the maintainers are available and responsive.

Presumably someone in core can move it along.

PS: I am volunteering to be a maintainer going forward.

**Comment by isuruf** [comment]
Thanks for volunteering

**Comment by CJ-Wright** [comment]
Could you please merge or close the other bot PRs? (otherwise this won't get bot version bumps)

**Comment by ChrisBarker-NOAA** [comment]
On Tue, Dec 17, 2019 at 10:05 AM Christopher J. Wright <
notifications@github.com> wrote:

> Could you please merge or close the other bot PRs?
>
done.

thanks all!

-CHB

**Comment by CJ-Wright** [comment]
Thank you!

**Pull request merged**
